import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { Toaster } from "sonner";
import { lazy } from "react";
const inter = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Memory Game",
  description: "Generated by create next app",
};
const Header = lazy(() => import("../components/Header"));

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div id="bg" className="w-full h-screen overflow-hidden">
            <Header />
            {children}
            <Toaster richColors />
          </div>
        </Provider>
      </body>
    </html>
  );
}
